#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#removeActivity:
#    path: /removeactivite/{id}/removeActivity
#    controller: App\Controller\ActiviteController::delete


